## Import Necessary Libraries

In [17]:
import pandas as pd
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver

### working with Webdriver to get source of Page

In [18]:
options = webdriver.ChromeOptions()

browser = webdriver.Chrome("C:\chromedriver\chromedriver.exe", options = options)
browser.get("https://www.totaljobs.com/jobs/cleaner/in-london?radius=0")

### Beautifying the source Page

In [24]:
src = browser.page_source
soup=BeautifulSoup(src)

#### Getting necessary elements from the page

In [25]:
company = soup.find_all('div', attrs = {'class' : 'sc-AxheI cOZDZM'})
job = soup.find_all('h2', attrs = {'class' : 'sc-fzqARJ iyolKq'})
city_zip = soup.find_all('li', attrs = {'class' : 'sc-fznzOf fKAMhD'})

In [27]:
job_title = []
company_name = []
area = []

for i in range(len(job)):
    job_title.append(job[i].text.strip())
    company_name.append(company[i].text.strip())
    area.append(city_zip[i].text.strip())

In [35]:
options = webdriver.ChromeOptions()
options.add_argument("--incognito")

browser = webdriver.Chrome("C:\chromedriver\chromedriver.exe", options = options)

browser.get("https://www.totaljobs.com/jobs/cleaner/in-london?radius=0&page=2")
src = browser.page_source
soup=BeautifulSoup(src)
company = soup.find_all('div', attrs = {'class' : 'sc-AxheI cOZDZM'})
job = soup.find_all('h2', attrs = {'class' : 'sc-fzqARJ iyolKq'})
city_zip = soup.find_all('li', attrs = {'class' : 'sc-fznzOf fKAMhD'})
for i in range(len(job)):
        job_title.append(job[i].text.strip())
        company_name.append(company[i].text.strip())
        area.append(city_zip[i].text.strip())

#### Iterating over all pages of Site

In [32]:
df = pd.DataFrame(list(zip(company_name, job_title, area)), columns=['Company_Name','Role','Area/Zip'])
df

,Company_Name,Role,Area/Zip
0,MCG Construction,Welfare Cleaner,"Wembley Park, HA9 8AD"
1,Property Management Recruitment (PMR),Cleaner + Caretaker - Temporary,"EC1, City of London"
2,Property Management Recruitment,Cleaner + Caretaker - Temporary,"City of London, London"
3,Property Management Recruitment (PMR),Temporary Caretaker/Cleaner,London
4,Property Management Recruitment,Temporary Caretaker/Cleaner,London
5,SkyBlue Solutions,Cleaner,"N7, North London, N7 8TT"
6,Property Management Recruitment (PMR),Temporary Cleaner/Caretaker,"IG1, Ilford"
7,RECRUITMENTiQ,Cleaner,London
8,Hays,CLEANER - LONDON,"Mile End, E1"
9,Hays,CLEANER - EAST LONDON,"Mile End, E1"
10,Service Care Solutions,Cleaner,"N1, North London"
11,Brook Street UK,Cleaner,"N1, North London"
12,Abbatt Property Recruitment,Cleaner - Permanent - E14,London
13,Abbatt Property Recruitment,Temporary Cleaner,"City of London, London"
14,Abbatt Property Recruitment,Cleaner,London
15,Abbatt Property Recruitment,Cleaner,London
16,Pertemps London,LIBRARY CLEANER WEST LONDON,"Central London, London"
17,Wild Recruitment,Cleaner,"NW1, North West London"
18,Setsquare,Cleaner,"North West London, London"
19,Ontrak Recruitment,Cleaner,"Wimbledon, SW19 7NL"
20,Swanstaff Recruitment Ltd,Cleaner,"St. Pauls Cray, BR5 3RT"
21,Stafforce,Cleaner,"East London, London"
22,Third Space,Male Cleaner - Third Space - Canary Wharf,"E14, East London, E14 5ER"
23,Property Management Recruitment (PMR),"Temporary Cleaner - Various Luxury Buildings, ...",London
24,Property Management Recruitment,"Temporary Cleaner - Various Luxury Buildings, ...",London

In [ ]:
print(df.head(20))
df.shape

### Creating a CSV file of finding data

In [33]:
df.to_csv('TotlaJobs.csv')